config/routes.rb
Rails.application.routes.draw do
  # User Authentication
  devise_for :users

  # Main Resources
  resources :assignments
  resources :students
  resources :contacts, only: [ :create ]

  # Static Pages
  get "faq", to: "static_pages#faq"
  get "about", to: "static_pages#about"
  root "static_pages#home"

  # Admin Routes
  namespace :admin do
    patch "users/:id", to: "admin#update_user", as: :update_user
  end
  get "admin/dashboard", to: "admin#dashboard", as: :dashboard
  get "admin/view_messages", to: "admin#view_messages", as: :view_messages

  # User Management
  resources :users, only: [ :index, :edit, :update, :show, :destroy ] do
    member do
      patch :change_role
    end
  end

  # Health Check and PWA
  get "up", to: "rails/health#show", as: :rails_health_check
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    has_one_attached :image
    has_rich_text :description

    validates :title, :description, :subject, :week_number, :due_date, :related_link, presence: true
    validates :due_date, uniqueness: true
    validate :image_format, if: -> { image.attached? }


    private

  def image_format
    if !image.content_type.in?(%w[image/jpeg image/png])
      errors.add(:image, "must be a JPEG or PNG file")
    end
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /assignments or /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1 or /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments or /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: "Assignment was successfully created." }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: "Assignment was successfully updated." }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1 or /assignments/1.json
  def destroy
    @assignment.destroy!

    respond_to do |format|
      format.html { redirect_to assignments_path, status: :see_other, notice: "Assignment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:title, :description, :subject, :week_number, :due_date, :related_link, :image)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment.html.erb
<div id="<%= dom_id assignment %>">
  <div class="card my-3"> 
    <div class="card-body">
      <div class="d-lg-flex align-items-center justify-content-between">
        <div class="lead">
          <p>
            <strong>Title : </strong>
            <%= assignment.title %>
          </p>

          <p>
            <strong>Subject : </strong>
            <%= assignment.subject %>
          </p>
        
          <p>
            <strong>Due date : </strong>
            <%= assignment.due_date %>
          </p>
        
          <p>
            <strong>Related link : </strong>
            <%= link_to assignment.related_link do %>
              <%= assignment.related_link %>
            <%end%>
          </p>
          
          <p>
              <strong>Description : </strong>
              <%= assignment.description %>
          </p>

        </div>
    
        <div class="text-center">
          <%= link_to assignment do %>
            <%= image_tag assignment.image , width:300 , height:300 %>
          <%end%>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/assignments/_form.html.erb
<%= form_with(model: assignment) do |form| %>
  <% if assignment.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
        <% assignment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row mb-3">
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :title, class:'form-label' %>
        <%= form.text_field :title, class:'form-control' %>
      </div>
    </div>
  
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :image, class:'form-label' %>
        <%= form.file_field :image, class:'form-control' %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :subject, class:'form-label' %>
        <%= form.text_field :subject, class:'form-control' %>
      </div>
    </div>
  
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :week_number, class:'form-label' %>
        <%= form.text_field :week_number, class:'form-control' %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :due_date, class:'form-label' %>
        <%= form.date_field :due_date, class:'form-control' %>
      </div>
    </div>
  
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :related_link, class:'form-label' %>
        <%= form.text_field :related_link, class:'form-control' %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-lg-12">
      <div class="form-group">
        <%= form.label :description, class:'form-label' %>
        <%= form.rich_text_area :description, class:'form-control' %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <%= form.submit class: "btn btn-primary rounded-0 fw-bold" %>
    <%= link_to "Go Back", assignments_path , class:'btn btn-outline-primary rounded-0 mx-2 fw-bold' %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<div class="container">
  <% content_for :title, "Editing assignment" %>
  <div class="card border-0">
    <div class="card-title text-center my-3 bg-secondary-subtle py-3">
      <h1>Edit <%= @assignment.week_number %> Assignment</h1>
    </div>
    <div class="card-body">
      <%= render "form", assignment: @assignment %>
    </div>
  </div>
</div>

app/views/assignments/index.html.erb
<div class="container">
<% content_for :title, "Assignments" %>
<div class="card border-0">
    <div class="card-title text-center my-3 bg-secondary-subtle py-3">
      <h1>Assignments</h1>
    </div>
    <% if user_signed_in? && current_user.admin?%>
    <div class="col-lg-12 my-3 d-flex justify-content-between align-items-center">
      <%= link_to "NEW ASSIGNMENT", new_assignment_path , class:'btn bg-primary rounded-0 text-white p-2 fw-bold' %>
      <div class="dropdown">
          <button class="btn btn-outline-primary dropdown-toggle rounded-0 fw-bold" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            View List In
          </button>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Table", assignments_path(view_type: "table") , class: "dropdown-item"%>
            </li>
            <li>
              <%= link_to "Card", assignments_path(view_type: "card") , class: "dropdown-item"%>
            </li>
          </ul>
      </div>
    </div>
    <% end %>
    <div class="card-body">
      <div id="assignments">
      <% if params[:view_type] != "card"%>
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th scope="col">Image</th>
              <th scope="col">Title</th>  
              <th scope="col">Subject</th>
              <th scope="col">Week</th>
              <th scope="col">Related Link</th>
              <th scope="col">Due Date</th>
              <th scope="col">Description</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @assignments.each do |assignment| %>
              <tr>
                <td>
                  <%= link_to assignment_path(assignment) do %>
                    <%= image_tag assignment.image, class: "img-thumbnail" , width:"100px" , height:"100px" %>
                  <% end %>
                </td>
                <td><%= assignment.title %></td>
                <td><%= assignment.subject %></td>
                <td><%= assignment.week_number %></td>
                <td><%= link_to("Link", sanitize(assignment.related_link), class: "text-decoration-none", target: "_blank") %></td>
                <td><%= assignment.due_date %></td>
                <td><%= assignment.description %></td>
                <td>
                  <% if user_signed_in? && current_user.admin?%>
                    <span class="d-flex gap-3">
                      <%= link_to "Edit", edit_assignment_path(assignment), class: "btn btn-warning" %>
                      <%= button_to "Delete", assignment, method: :delete, data: { turbo_confirm: "Are you sure to delete this assignment ?" }, class: "btn btn-danger" %>
                    </span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
   <% if [:view_type].present? && params[:view_type] == "card"%>
      <% @assignments.each do |assignment| %>
          <%= render assignment %>
      <% end %>
   <% end %>
      </div>
    </div>
</div>
</div>

app/views/assignments/new.html.erb
<div class="container">
  <% content_for :title, "New assignment" %>
  <div class="card border-0">
    <div class="card-title text-center my-3 bg-secondary-subtle py-3">
        <h1>NEW ASSIGNMENT</h1>
    </div>
    <div class="card-body">
      <%= render "form", assignment: @assignment %>
    </div>
  </div>
</div>

app/views/assignments/show.html.erb
<div class="container">

<div class="card border-0">
    <div class="card-title text-center my-3 bg-secondary-subtle py-3">
      <h1><%= @assignment.week_number %></h1>
    </div>
    <div class="card-body">
      <%= render @assignment %>
      <%= link_to "Go Back", assignments_path , class:"btn btn-outline-primary rounded-0 fw-bold" %>
    </div>
  </div>
</div>