config/routes.rb
Rails.application.routes.draw do
  # User Authentication
  devise_for :users

  # Main Resources
  resources :assignments
  resources :students
  resources :contacts, only: [ :create ]

  # Static Pages
  get "faq", to: "static_pages#faq"
  get "about", to: "static_pages#about"
  root "static_pages#home"

  # Admin Routes
  namespace :admin do
    patch "users/:id", to: "admin#update_user", as: :update_user
  end
  get "admin/dashboard", to: "admin#dashboard", as: :dashboard
  get "admin/view_messages", to: "admin#view_messages", as: :view_messages

  # User Management
  resources :users, only: [ :index, :edit, :update, :show, :destroy ] do
    member do
      patch :change_role
    end
  end

  # Health Check and PWA
  get "up", to: "rails/health#show", as: :rails_health_check
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/models/student.rb
class Student < ApplicationRecord
    has_one_attached :image

    validates :name, :email, :repository_link, :page_link, :phone, :education, :image, presence: true
    validates :email, :phone, :repository_link, :page_link, uniqueness: true
    validate :image_format, if: -> { image.attached? }
    # def image_url
    #     image.attached? ? url_for(image) : nil
    # end

    private

    def image_format
      if !image.content_type.in?(%w[image/jpeg image/png])
        errors.add(:image, "must be a JPEG or PNG file")
      end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_admin, only: [ :new, :create, :edit, :update, :destroy ]



  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_path, status: :see_other, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def check_admin
      unless current_user.admin?
        redirect_to students_path, alert: "You are not authorized to perform this action."
      end
    end

    def student_params
      params.require(:student).permit(:name, :email, :repository_link, :page_link, :phone, :image, :education)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row mb-3">
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :name, class:'form-label' %>
        <%= form.text_field :name , class:'form-control' %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :image, class:'form-label' %>
        <%= form.file_field :image , class:'form-control' %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :repository_link, class:'form-label' %>
        <%= form.text_field :repository_link , class:'form-control' %>
      </div>
    </div>
    
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :page_link, class:'form-label' %>
        <%= form.text_field :page_link , class:'form-control' %>
      </div>
    </div>
  </div>
  <div class="row mb-3">  
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :email, class:'form-label' %>
        <%= form.text_field :email , class:'form-control' %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :phone, class:'form-label' %>
        <%= form.text_field :phone , class:'form-control' %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :education, class:'form-label' %>
        <%= form.text_field :education , class:'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary rounded-0 fw-bold" %>
    <%= link_to "Go Back", students_path , class:'btn btn-outline-primary rounded-0 mx-2 fw-bold' %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <div class="card my-3">
    <div class="card-body">
      <div class="d-lg-flex align-items-center justify-content-between">
        <div>
          <p>
            <strong class="fs-4 fw-bold"> 
              <%= student.name %>
            </strong>
          </p>
          <% if user_signed_in? && current_user.admin? %>
          <p class="lead">
            <strong>Phone : </strong>
            <%= student.phone %>
          </p>
          
        
          <p class="lead">
          <strong>Education : </strong>
          <%= student.education %>
          </p>
          
        
          <p class="lead">
            <strong>Email : </strong>
            <%= student.email %>
          </p>

          <% end %>
          
          <p class="lead">
            <strong>Page link : </strong>
            <%= student.page_link %>
          </p>
    
          <p class="lead">
            <strong>Repository link : </strong>
            <%= student.repository_link %>
          </p>

          <p class="lead">
            <%= link_to "View #{student.name} profile" , student , class:'text-decoration-none'%>
          </p>
        
        </div>
    
        <div class="bg-primary-subtle rounded-2 text-center">
          <%= link_to student do %>
            <% if student.image.attached? %>
             <%= image_tag student.image, width: 200, height:220 %>
            <% else %>
             No image
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div> 
</div>

app/views/students/edit.html.erb
<div class="container">
  <% content_for :title, "Editing student" %>
  <div class="card border-0">
      <div class="card-title text-center my-3 bg-secondary-subtle py-3">
        <h1>Edit</h1>
      </div>
      <div class="card-body">
        <%= render "form", student: @student %>
      </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="container">
  <% content_for :title, "Students" %>
  <div class="card border-0">
    <div class="card-title text-center my-3 bg-secondary-subtle py-3">
      <h1>STUDENTS</h1>
    </div>
    <div class="card-body">
      <% if user_signed_in? && current_user.admin? %>
        <div class="col-lg-12 my-3 d-flex justify-content-between align-items-center">
          <%= link_to "NEW STUDENT", new_student_path, class: 'btn bg-primary rounded-0 text-white p-2 fw-bold' %>
          <div class="dropdown">
            <button class="btn btn-outline-primary dropdown-toggle rounded-0 fw-bold" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              View List In
            </button>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Table", students_path(view_type: "table"), class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "Card", students_path(view_type: "card"), class: "dropdown-item" %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>

      <div id="students">
        <% if params[:view_type] != "table" %>
          <% @students.each do |student| %>
            <%= render student %>
          <% end %>
        <% end %>

        <% if params[:view_type].present? && params[:view_type] == "table" %>
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th scope="col">Image</th>
                  <th scope="col">Name</th>
                  <th scope="col">Email</th>  
                  <th scope="col">Repository Link</th>
                  <th scope="col">Page Link</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @students.each do |student| %>
                  <tr>
                    <td>
                      <%= link_to student_path(student) do %>
                        <%= image_tag student.image, class: "img-thumbnail", width: "100px", height: "100px" %>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to student_path(student) , class:'text-decoration-none' do %>
                         <strong><%= student.name %></strong>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to student_path(student) , class:'text-decoration-none' do %>
                        <%= student.email %>
                      <% end %>
                    </td>
                    <td><%= link_to "Repository", sanitize(student.repository_link), class: 'text-decoration-none' %></td>
                    <td><%= link_to "Page", sanitize(student.page_link), class: 'text-decoration-none' %></td>
                    <td>
                      <% if user_signed_in? && current_user.admin? %>
                        <span class="d-flex gap-3">
                          <%= link_to "Edit", edit_student_path(student), class: "btn btn-warning" %>
                          <%= button_to "Delete", student, method: :delete, data: { turbo_confirm: 'Are you sure to delete this student?' }, class: "btn btn-danger" %>
                        </span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<div class="container">
  <% content_for :title, "New student" %>
  <div class="card border-0">
  
      <div class="card-title text-center my-3 bg-secondary-subtle py-3">
      <h1>NEW STUDENT</h1>
      </div>
  
      <div class="card-body">
        <%= render "form", student: @student %>
      </div>
      
  </div>
</div>

app/views/students/show.html.erb
<div class="container">
  <div class="card border-0">
      <div class="card-title text-center my-3 bg-secondary-subtle py-3">
        <h1><%= @student.name %></h1>
      </div>
      <div class="card-body">
        <%= render @student %>
        <div class="d-flex gap-3">
          <%= link_to "Go Back", students_path , class:"btn btn-outline-primary rounded-0 fw-bold" %>
        </div>
      </div>
   
  </div>
</div>